apiVersion: v1
kind: Secret
metadata:
  name: oncall-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DB_HOST:               "${DB_HOST}"
  DB_PORT:               "5432"
  DB_NAME:               "notes"
  DB_USER:               "notes"
  DB_PASSWORD:           "${DB_PASSWORD}"
  REDIS_MODE:            "sentinel"
  REDIS_SENTINEL_HOSTS:  "${REDIS_SENTINEL_HOSTS}"
  REDIS_SENTINEL_MASTER: "mymaster"
  REDIS_TTL:             "30"
  APP_PORT:              "8080"
  LOG_DIR:               "/var/log/oncall-service"
